CSCI 205 - Programming with Databases/hopes_app/hopes_app/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponse
from django.conf.urls import handler404
from django.views.defaults import page_not_found

urlpatterns = [
    path("admin/", admin.site.urls),
    path('hopesdreams/', include('hopesdreams.urls')) # localhost:8000/hopesdreams/
]

CSCI 205 - Programming with Databases/hopes_app/hopesdreams/urls.py
from django.urls import path
from . import views

app_name = 'hopesdreams'
urlpatterns = [
    # localhost:8000/hopesdreams/
    path('', views.index),

    
    # localhost:8000/hopesdreams/dreamer/new/

    path('dreamer/new/', views.adddreamer, name = 'dreamer-add'),

    # localhost:8000/hopesdreams/dreamers/

    path('dreamers/', views.listdreamer, name = 'dreamer-list'),

    # localhost:8000/hopesdreams/dreamer/<id>/
    
    path('dreamer/<int:pk>/', views.detaildreamer, name = 'dreamer-detail'),


]

CSCI 205 - Programming with Databases/hopes_app/hopesdreams/models.py
from django.db import models

# Create your models here.
# creates the code for making the tables


class Dreamer(models.Model):
    firstname = models.CharField(max_length = 20)
    lastname = models.CharField(max_length = 20)
    def __str__(self):
        return f'Dreamer #{self.id} Name: {self.firstname} {self.lastname}'
   
class Dream(models.Model):
    Type = [
        ('Personal', 'Personal'), 
        ('Professional', 'Professional'),
    ]

    type = models.CharField(
        max_length=50,
        choices=Type
    )

    description = models.CharField(max_length = 50)
    dreamer = models.ForeignKey(Dreamer, on_delete = models.CASCADE)
    def __str__(self):
        return f'Dreamer {self.dreamer.firstname} {self.dreamer.lastname}, Type: {self.type}, Description: {self.description}'

CSCI 205 - Programming with Databases/hopes_app/hopesdreams/forms.py
from django.forms import ModelForm
from .models import Dreamer

class DreamerForm(ModelForm):
    class Meta:
        model = Dreamer
        fields = ['firstname', 'lastname']

CSCI 205 - Programming with Databases/hopes_app/hopesdreams/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from .models import Dreamer, Dream
from django.contrib import messages
from .forms import DreamerForm
# Create your views here.



def index(request):
    return render(request, 'hopesdreams/base_template.html')

def listdreamer(request):
    dreamerlist = Dreamer.objects.all()
    context = {'dreamerlist': dreamerlist}
    return render(request, 'hopesdreams/dreamer_list.html', context)

def adddreamer(request):
    if request.method == 'GET':
        cf = DreamerForm()
    elif request.method == 'POST':
        cf = DreamerForm(request.POST)
        if cf.is_valid():
            cf.save()
            return redirect('hopesdreams:dreamer-list')
    context = {'form': cf, 'actionname': 'Add'}
    return render(request, 'hopesdreams/dreamer_form.html', context)




def detaildreamer(request, pk):
    c = Dreamer.objects.get(id = pk)
    context = {'dreamer': c}
    return render(request, 'hopesdreams/dreamer_detail.html', context)

CSCI 205 - Programming with Databases/hopes_app/hopesdreams/templates/hopesdreams/base_template.html
<!DOCTYPE html>

<html>

    <head>
        <meta charset = "utf-8">
        <title>HopesApp - Hopesdreams - {% block pagetitle %}{% endblock %}</title>

    </head>

    <body>
        <h1>Hopes and Dreams</h1>
        <p>Believe in Yourself</p>

        <main>
            {% block maincontent %}{% endblock %}
        </main>
    </body>
</html>

CSCI 205 - Programming with Databases/hopes_app/hopesdreams/templates/hopesdreams/dreamer_detail.html
{% extends 'hopesdreams/base_template.html' %}

{% block pagetitle %}{{dreamer.firstname}} {{dreamer.lastname}}{% endblock %}

{% block maincontent %}
<h2>Dreamer Details</h2>

<ul>
    <li>Name: {{ dreamer.firstname }}  {{dreamer.lastname}}</li>    
</ul>

{% if dreamer.dream_set.exists %}

<h3>Dreams</h3>

<ul>
    {% for dream in dreamer.dream_set.all %}

    <li>{{ dream.description }}</li>
    {% endfor %}

</ul>
{% else %}

<p>No addresses found for this customer.</p>

{% endif %}

{% endblock %}

CSCI 205 - Programming with Databases/hopes_app/hopesdreams/templates/hopesdreams/dreamer_form.html
{% extends 'hopesdreams/base_template.html' %}

{% block pagetitle %}Dreamer Form {% endblock %}

{% block maincontent %}

<h2>Dreamer</h2>

<form method = 'post'>
    {% csrf_token %}
    {{ form.as_ul }}
    <input type = 'submit' value = 'Submit'>
</form>


{% endblock %}

CSCI 205 - Programming with Databases/hopes_app/hopesdreams/templates/hopesdreams/dreamer_list.html
{% extends 'hopesdreams/base_template.html' %}

{% block pagetitle %}Dreamers{% endblock %}

{% block maincontent %}
<h2>Dreamers</h2>
<ul>
    {% for dreamer in dreamerlist %}
        <li>#{{dreamer.id}} - {{dreamer.firstname}} {{ dreamer.lastname }} 
        </li>
    {% endfor %}
</ul>
{% endblock %}